### PR TITLE
Updating plot_deformedshape()

### PR DESCRIPTION
**Pull request by u-anurag**
* Gets displacement data using _readNodeDispData() function.
* Updated command takes a Model name as an input instead of a filename.
* Added warnings for insufficient input.
* Added '-time' to all the recorders to plot the deformed shape at a specific time of analysis.

### CODE REVIEW

**Comment by u-anurag** [comment]
image

**Comment by u-anurag** [comment]
image

**Comment by u-anurag** [comment]
@cslotboom I have finished updating `Get_Rendering.py`. You can make the necessary changes to the animation library.

**Comment by cslotboom** [comment]
Okay great! I'll take a look and make the necessary updates.

**Pull request merged**
