### PR TITLE
Adding option to monitor specific elements

### PR DESCRIPTION
**Pull request by u-anurag**
A list of element tags is supplied by the user to plot_deformedshape() function. This will plot the deformed shape of the specified elements only. Useful for monitoring deformation of specific locations in large structures since Matplotlib 3D plot can not zoom in to a specific location. It was helpful for my research on rocking bridge columns.

### CODE REVIEW

**Comment by u-anurag** [comment]
@cslotboom check this input option. What do you think?

**Review by cslotboom — APPROVED** [review]
Hey - that's annoying that it's difficult to zoom in on objects. That will make monitoring a big model more difficult.

The addition makes sense. I see no problems, but it might be cleaner to standardize the following code into a function, as it's used a few times.

```
if adjustViewport == "yes":
	for node in Nodes:
		if node not in adjusted_NodeArray[:,0]:
			adjusted_NodeArray[adjNodeNum,0:1] = nodecoordsFinal(node)
```

It would be great if we could avoid going down 4 levels in the indentation, but I can't think of a way..

**Comment by u-anurag** [comment]
> The addition makes sense. I see no problems, but it might be cleaner to standardize the following code into a function, as it's used a few times.

You are right. I'll work on that. Also, do you think axis.getlimits() can let us zoom in to a specific portion of the 3D figure?

**Comment by cslotboom** [comment]
I think it's possible, I would have to do some testing.
There are some camera adjustment tools that might also help: https://stackoverflow.com/questions/12904912/how-to-set-camera-position-for-3d-plots-using-python-matplotlib

Long term, I'm not sure how much effort we would want to put into the matplotlib 3D tools though.
There are some known issues with matplotlib's 3D backend, for example: https://matplotlib.org/mpl_toolkits/mplot3d/faq.html#my-3d-plot-doesn-t-look-right-at-certain-viewing-angles.

**Comment by u-anurag** [comment]
I know Matplotlib is not the appropriate tool for this but we are bound by the limitations. Manually setting the camera position is a pain. I think this selective/monitoring element option will give us better output.

**Comment by cslotboom** [comment]
I think this is a good feature regardless. It will also improve the rendering speed.

Agreed about Matplotlib. At a some point we will have to decide between trying to fix challenges with matplotlib, or moving to another platform. We're definitely not there yet though! Matplotlib will work adequately for now.

**Pull request merged**
